name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: make
      - name: Store result
        uses: actions/upload-artifact@v4
        with:
          name: toil
          path: toil
          if-no-files-found: error
