name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version number
        required: true
        type: string
      branch:
        description: Branch name
        required: true
        type: string
        default: main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{inputs.version}}
          target_commitish: ${{inputs.branch}}
